version: '3'

services:
  znca-api:
    # build: .
    image: samuelthomas2774/nxapi-znca-api
    command:
      - android-frida-server
      - ${ZNCA_API_ANDROID_DEVICE:-redroid:5555}
      - --exec-command
      - ${ZNCA_API_EXEC_COMMAND:-}
      # - --adb-root
      - --frida-server-path
      - ${ZNCA_API_FRIDA_SERVER_PATH:-/system/bin/frida-server}
      - --start-method
      - ${ZNCA_API_APP_START_METHOD:-spawn}
      - --listen
      - '[::]:80'
    restart: unless-stopped
    depends_on:
      - redroid
    labels:
      traefik.enable: true
      traefik.http.routers.nxapi-znca.entrypoints: websecure
      traefik.http.routers.nxapi-znca.rule: Host(`${TRAEFIK_HOST:-nxapi.ta.fancy.org.uk}`) && PathPrefix(`/api/znca/`)
      traefik.http.routers.nxapi-znca.tls: true
      traefik.http.services.nxapi-znca.loadbalancer.server.port: 80
    environment:
      DEBUG: '*,-express:*,-body-parser:*'
    volumes:
      - data:/data
    healthcheck:
      test: [ "ENTRYPOINT", "curl", "http://[::1]:80/api/znca/health" ]
      timeout: 45s
      interval: 10s
      retries: 10

  #
  # Before starting the znca-api service, start the redroid service and:
  #
  # - Rename /system/xbin/su to /system/xbin/_su (might not be necessary on all redroid versions)
  # - Install the Nintendo Switch Online app
  # - Install frida-server (make sure it is executable!)
  #
  # The binder and ashmem kernel modules must be loaded on the host before
  # this service starts (see https://github.com/remote-android/redroid-doc)
  #

  redroid:
    build:
      context: redroid-coral
      args:
        CORAL_APK_URL: ${CORAL_APK_URL}
        # shasum -a 256 com.nintendo.znca-2.4.0.apk
        CORAL_APK_HASH_SHA256: da0cf5647a855cadf7f69e02815d3fdf9d7ab3d568fe809f8b8ff47598016d0d
    command: ro.secure=0
    restart: unless-stopped
    privileged: true
    # ports:
    #   - 5555:5555/tcp
    volumes:
      - android-data:/data

volumes:
  data:
  android-data:
