version: '3'

services:
  znca-api:
    # build: .
    image: samuelthomas2774/nxapi-znca-api
    command:
      - android-frida-server
      - redroid
      - --resolve-multiple-devices
      - --frida-server-path
      - /system/bin/frida-server
      - --start-method
      - ${ZNCA_API_APP_START_METHOD:-spawn}
      - --listen
      - '[::]:80'
      - --metrics
    restart: unless-stopped
    depends_on:
      - redroid
    labels:
      traefik.enable: true
      traefik.http.routers.nxapi-znca.entrypoints: websecure
      traefik.http.routers.nxapi-znca.rule: Host(`${TRAEFIK_HOST:-nxapi.ta.fancy.org.uk}`) && PathPrefix(`/api/znca/`)
      traefik.http.routers.nxapi-znca.tls: true
      traefik.http.services.nxapi-znca.loadbalancer.server.port: 80
    environment:
      DEBUG: '*,-express:*,-body-parser:*'
    volumes:
      - data:/data
    healthcheck:
      test: [ "CMD", "curl", "http://127.0.0.1:80/api/znca/health" ]
      timeout: 45s
      interval: 10s
      retries: 10

  # The binder and ashmem kernel modules must be loaded on the host before
  # this service starts (see https://github.com/remote-android/redroid-doc)
  redroid:
    build:
      context: redroid-coral
      args:
        CORAL_APK_URL: ${CORAL_APK_URL}
        # shasum -a 256 com.nintendo.znca-2.4.0.apk
        CORAL_APK_HASH_SHA256: ${CORAL_APK_HASH_SHA256:-da0cf5647a855cadf7f69e02815d3fdf9d7ab3d568fe809f8b8ff47598016d0d}
    restart: unless-stopped
    privileged: true
    healthcheck:
      test: [ "CMD", "sh", "-c", "[ \"\\`netstat -lnt | awk '\\$6 == \"LISTEN\" && \\$4 ~ /\\:5555$/'\\`\" != \"\" ]" ]
      timeout: 10s
      start_period: 2m

volumes:
  data:
